[package]
name = "tanque_backend"
version = "0.1.0"
edition = "2021"

# Dependências
[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-files = "0.6"
rusqlite = { version = "0.25.4", features = ["bundled"] }
thiserror = "1.0"
